const books = [
  {
    id: 1,
    title: "Belajar JavaScript Dasar",
    author: "Andi Prasetyo",
    year: 2021,
    description: "Panduan lengkap untuk pemula yang ingin belajar JavaScript dari nol.",
    image: "https://example.com/images/js-dasar.jpg",
    price: "Rp 98.000",
    coverId: 15255806,
    from: "#0f766e",
    to: "#134e4a",
  },
  {
    id: 2,
    title: "React untuk Pemula",
    author: "Dina Sari",
    year: 2022,
    description: "Mengenal konsep dan praktik membuat aplikasi React modern.",
    image: "https://example.com/images/react-pemula.jpg",
    price: "Rp 145.000",
    coverId: 8634250,
    from: "#b45309",
    to: "#78350f",
  },
  {
    id: 3,
    title: "Node.js untuk Backend",
    author: "Rizky Hidayat",
    year: 2023,
    description: "Belajar membangun API, server, dan sistem backend dengan Node.js.",
    image: "https://example.com/images/node-backend.jpg",
    price: "Rp 110.000",
    coverId: 15094936,
    from: "#9f1239",
    to: "#4c0519",
  },
  {
    id: 4,
    title: "CSS Modern untuk Web",
    author: "Nadia Putri",
    year: 2021,
    description: "Memahami layout, responsif, animasi, dan styling modern untuk website.",
    image: "https://example.com/images/css-modern.jpg",
    price: "Rp 90.000",
    coverId: 10872657,
    from: "#1d4ed8",
    to: "#1e1b4b",
  },
  {
    id: 5,
    title: "Database MySQL Dasar",
    author: "Budi Santoso",
    year: 2020,
    description: "Mempelajari struktur data, query, dan relasi database dengan MySQL.",
    image: "https://example.com/images/mysql-dasar.jpg",
    price: "Rp 85.000",
    coverUrl: "https://bukukita.com/babacms/displaybuku/118789_f.jpg",
    from: "#c2410c",
    to: "#431407",
  },
  {
    id: 6,
    title: "PHP untuk Pemula",
    author: "Arif Rahman",
    year: 2022,
    description: "Tutorial praktis pembuatan website dinamis dan backend dengan PHP.",
    image: "https://example.com/images/php-pemula.jpg",
    price: "Rp 80.000",
    coverId: 4317176,
    from: "#4d7c0f",
    to: "#1a2e05",
  },
  {
    id: 7,
    title: "UI/UX untuk Developer",
    author: "Jihan Aulia",
    year: 2023,
    description: "Menerapkan prinsip desain yang mudah dipahami untuk membangun produk yang ramah pengguna.",
    image: "https://example.com/images/uiux-developer.jpg",
    price: "Rp 120.000",
    coverUrl: "https://down-id.img.susercontent.com/file/id-11134207-7ra0j-mb688ifz4koka3",
    from: "#7e22ce",
    to: "#3b0764",
  },
  {
    id: 8,
    title: "Git & GitHub untuk Tim",
    author: "Yusuf Kurniawan",
    year: 2021,
    description: "Panduan kolaborasi proyek digital menggunakan Git dan GitHub secara efektif.",
    image: "https://example.com/images/git-github.jpg",
    price: "Rp 95.000",
    coverId: 12810708,
    from: "#0369a1",
    to: "#082f49",
  },
  {
    id: 9,
    title: "Testing Aplikasi Web",
    author: "Lia Pratama",
    year: 2024,
    description: "Mengenal teknik testing untuk menjaga kualitas aplikasi web dari bug dan error.",
    image: "https://example.com/images/testing-web.jpg",
    price: "Rp 110.000",
    coverId: 13903116,
    from: "#be123c",
    to: "#1f2937",
  },
];

export default books;
